# Generated by Django 3.0.7 on 2020-06-25 18:19

import builtins
from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200625_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('productid', models.IntegerField(verbose_name=web.models.Product(builtins.id))),
                
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now=True, verbose_name='Дата оформления')),
                ('cnt', models.CharField(max_length=50, verbose_name='Количество приобретаемого товара')),
            ],
        ),
        migrations.AlterField(
            model_name='products',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sellers',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
