# Generated by Django 3.0.7 on 2020-06-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200625_2119'),
    ]

    operations = [
        
        migrations.RemoveField(
            model_name='order',
            name='productid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sellerid',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(verbose_name='Дата оформления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
