# Generated by Django 3.0.7 on 2020-06-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200625_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderid',
            field=models.IntegerField(blank=True, null=True, verbose_name='orderid'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
