# Generated by Django 3.0.7 on 2020-06-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20200625_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='product_id'),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='seller_id'),
        ),
    ]
