# Generated by Django 3.0.7 on 2020-06-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20200625_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='zapros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('huawei', 'Huawei'), ('dexp', 'Dexp'), ('aplle', 'Apple'), ('nokia', 'Nokia'), ('electrolux', 'Electolux')], max_length=20, verbose_name='Брэнд'),
        ),
    ]
