# Generated by Django 3.0.7 on 2020-06-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20200626_1516'),
    ]

    operations = [
    
    ]
