# Generated by Django 3.0.7 on 2020-06-26 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20200626_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_id',
        ),


        migrations.RemoveField(
            model_name='product',
            name='id',
        ),

        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=models.PROTECT, to='web.Product', verbose_name='productid'),
        ),

        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False, verbose_name='id'),
            preserve_default=False,
        ),
        
    ]
