# Generated by Django 3.0.7 on 2020-06-29 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20200626_2253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderid',
        ),
        migrations.RemoveField(
            model_name='product',
            name='productid',
        ),
    
        migrations.AddField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, verbose_name='ID'),
            preserve_default=False,
        ),

        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True,  on_delete=models.PROTECT, to='web.Product', verbose_name='productid'),
            preserve_default=False,
        ),


        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products_images/')),
                ('is_main', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Product', models.ForeignKey(blank=True, on_delete=models.PROTECT, to='web.Product')),
            ],
        ),
    ]
