# Generated by Django 3.0.7 on 2020-07-01 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20200630_2008'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, on_delete=models.PROTECT, to='web.ProductBrand', verbose_name='Брэнд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True,  on_delete=models.PROTECT, to='web.ProductCategory', verbose_name='Категория'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProductInBasket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, default=None, max_length=128, null=True)),
                ('nmb', models.IntegerField(default=1)),
                ('price_per_item', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True,  on_delete=models.PROTECT, to='web.Order')),
                ('product', models.ForeignKey(blank=True,  on_delete=models.PROTECT, to='web.Product')),
            ],
        ),
    ]
