# Generated by Django 3.0.7 on 2020-07-01 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20200701_1723'),
    ]

    operations = [
    
    ]
