# Generated by Django 3.0.7 on 2020-07-01 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20200701_1737'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sellers',
        ),
        migrations.RemoveField(
            model_name='order',
            name='seller_id',
        ),
    ]
